# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/

###

# получение токена
# @name login
POST http://localhost:8000//api-token-auth/
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}



###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 20d37529af93ea8ff26e062b3292cabfab9d1cdc

{
  "title": "Шкаф IKEA",
  "description": "Срочно",
  "status": "OPEN"
}


###

# попытка поменять свое объявление 
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 20d37529af93ea8ff26e062b3292cabfab9d1cdc

{
  "status": "CLOSED"
}

###

# попытка поменять чужое объявление 
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token b41d40fb2c298ecc273736bd03e548a3811bacef

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json